# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 08:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default=b'Area')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField(default=b'Untitled')),
                ('description', models.TextField(default=b'No description')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField(default=b'Untitled')),
                ('description', models.TextField(default=b'No description')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('published', models.DateTimeField(blank=True, null=True)),
                ('area', models.ManyToManyField(related_name='areaField', to='scimap.Area')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fromNodes', models.ManyToManyField(blank=True, related_name='_node_fromNodes_+', to='scimap.Node')),
                ('subArea', models.ManyToManyField(related_name='subAreaField', to='scimap.Area')),
                ('toNodes', models.ManyToManyField(blank=True, related_name='_node_toNodes_+', to='scimap.Node')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField(default=b'Untitled')),
                ('nodes', models.ManyToManyField(to='scimap.Node')),
            ],
        ),
        migrations.CreateModel(
            name='SubArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default=b'Subarea')),
            ],
        ),
        migrations.AddField(
            model_name='link',
            name='fromNode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scimap.Node'),
        ),
        migrations.AddField(
            model_name='link',
            name='toNode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scimap.Node'),
        ),
        migrations.AlterUniqueTogether(
            name='link',
            unique_together=set([('fromNode', 'toNode')]),
        ),
    ]
