# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scimap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='inc',
        ),
        migrations.RemoveField(
            model_name='node',
            name='out',
        ),
        migrations.AddField(
            model_name='node',
            name='fromNodes',
            field=models.ManyToManyField(blank=True, related_name='_node_fromNodes_+', to='scimap.Node'),
        ),
        migrations.AddField(
            model_name='node',
            name='toNodes',
            field=models.ManyToManyField(blank=True, related_name='_node_toNodes_+', to='scimap.Node'),
        ),
    ]
