# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scimap', '0002_node_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='title',
            field=models.TextField(verbose_name=b''),
        ),
    ]
