# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 23:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('scimap', '0002_auto_20170715_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField(default=b'Untitled')),
                ('description', models.TextField(default=b'No description')),
            ],
        ),
        migrations.AddField(
            model_name='node',
            name='toNodeLinkInfo',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='node',
            name='subArea',
            field=models.ManyToManyField(related_name='SubArea', to='scimap.Area'),
        ),
        migrations.AddField(
            model_name='link',
            name='fromNode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scimap.Node'),
        ),
        migrations.AddField(
            model_name='link',
            name='toNode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scimap.Node'),
        ),
        migrations.AlterUniqueTogether(
            name='link',
            unique_together=set([('fromNode', 'toNode')]),
        ),
    ]
