# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scimap', '0003_auto_20170717_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='area',
            field=models.ManyToManyField(related_name='areaField', to='scimap.Area'),
        ),
        migrations.AlterField(
            model_name='node',
            name='subArea',
            field=models.ManyToManyField(related_name='subAreaField', to='scimap.Area'),
        ),
    ]
