# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scimap', '0003_auto_20170710_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='title',
            field=models.TextField(),
        ),
    ]
