# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scimap', '0004_auto_20170718_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='description',
            field=models.TextField(default=b'Description'),
        ),
    ]
