# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 00:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scimap', '0004_auto_20170717_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='toNodeLinkInfo',
        ),
    ]
