# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scimap', '0004_auto_20170710_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='slug',
            field=models.TextField(blank=True, null=True),
        ),
    ]
