# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('scimap', '0005_node_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='id',
            field=models.TextField(default=uuid.UUID('3d916f6a-bf8a-4875-a84f-bc6b77413c15'), primary_key=True, serialize=False),
        ),
    ]
