# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scimap', '0007_auto_20170712_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='inc',
            field=models.ManyToManyField(blank=True, null=True, related_name='_node_inc_+', to='scimap.Node'),
        ),
        migrations.AlterField(
            model_name='node',
            name='out',
            field=models.ManyToManyField(blank=True, null=True, related_name='_node_out_+', to='scimap.Node'),
        ),
    ]
