# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 22:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scimap', '0010_auto_20170714_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='node',
            name='published',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
